// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXi8WqNFHNwtp0-3SNEsFw_5CYxEQMpE',
    appId: '1:877773124498:web:2c1f254fa22de05d97474b',
    messagingSenderId: '877773124498',
    projectId: 'halaby-app',
    authDomain: 'halaby-app.firebaseapp.com',
    storageBucket: 'halaby-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-LBIbEQDNKJrCfkHbO2DFVVtpeOvkSA',
    appId: '1:877773124498:android:6347f0a52bb86b3197474b',
    messagingSenderId: '877773124498',
    projectId: 'halaby-app',
    storageBucket: 'halaby-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvmUTwQVeUyLbINW8alRmDDHVfvoEUws',
    appId: '1:877773124498:ios:74ed29a3e615d2b497474b',
    messagingSenderId: '877773124498',
    projectId: 'halaby-app',
    storageBucket: 'halaby-app.firebasestorage.app',
    iosBundleId: 'com.example.halabyDoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvmUTwQVeUyLbINW8alRmDDHVfvoEUws',
    appId: '1:877773124498:ios:74ed29a3e615d2b497474b',
    messagingSenderId: '877773124498',
    projectId: 'halaby-app',
    storageBucket: 'halaby-app.firebasestorage.app',
    iosBundleId: 'com.example.halabyDoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXi8WqNFHNwtp0-3SNEsFw_5CYxEQMpE',
    appId: '1:877773124498:web:19862127f60fa4ec97474b',
    messagingSenderId: '877773124498',
    projectId: 'halaby-app',
    authDomain: 'halaby-app.firebaseapp.com',
    storageBucket: 'halaby-app.firebasestorage.app',
  );
}
